'use strict';

// Harness emitters — the per-harness file writers (Claude Code, Codex,
// OpenCode) plus the shared-asset copier. Extracted from bin/concertino
// verbatim; shared by sync, diff, and eject.

const fs = require('fs');
const path = require('path');

const { resolveModel, isOllamaRouted } = require('../config');
const {
  ADAPTERS, VERSION, green,
  read, exists, write, copy, readRoleFile,
} = require('./shared');
const { renderBody } = require('./render');

// ---------- harness emitters ---------------------------------------------
function emitClaude(c, out, core, dry) {
  const meta = JSON.parse(read(path.join(ADAPTERS, 'claude-code', 'agents.json')));
  for (const role of ['orchestrator', 'executor', 'evaluator', 'skeptic', 'auditor']) {
    const r = meta.roles[role];
    let tools = r.baseTools.slice();
    if (r.usesUi && c.ui.enabled && c.ui.tool === 'playwright') tools = tools.concat(meta.playwrightTools);
    const mcp = (r.mcpTools && r.mcpTools[c.ticketProvider.kind]) || [];
    tools = tools.concat(mcp);
    const body = renderBody(readRoleFile(role, out, core), c, 'claude-code');
    const desc = r.description.split('{{project}}').join(c.project.name);
    const model = resolveModel(c, 'claude-code', role);
    const fm = [
      '---',
      '# concertino:sync v' + VERSION,
      'name: concertino-' + role,
      'description: >-',
      '  ' + desc,
      'model: ' + model,
      'color: ' + r.color,
      'tools:',
      ...tools.map((t) => '  - ' + t),
      '---',
      ''
    ].join('\n');
    write(path.join(out, '.claude', 'agents', 'concertino-' + role + '.md'), fm + body, dry);
  }
  const cmd = read(path.join(ADAPTERS, 'claude-code', 'command.md'))
    .split('{{project}}').join(c.project.name)
    .split('{{idExample}}').join(c.ticketProvider.idExample);
  write(path.join(out, '.claude', 'commands', 'concertino-deliver.md'), cmd, dry);
}

// A role's rendered `.codex/agents/*.toml` gets `model_provider = "ollama"`
// only when it is Ollama-routed (design.md Decision 2/3: "codex" in
// providers.ollama.harnesses AND no explicit models.codex.<role> override) —
// else the placeholder renders empty, preserving today's file untouched.
function codexModelProviderLine(c, role) {
  return isOllamaRouted(c, 'codex', role) ? 'model_provider = "ollama"\n' : '';
}

// Merges `blockText` into `existing` at a `<!-- CONCERTINO:BEGIN/END -->`
// region (creating one at the end if none is present yet), so hand-authored
// content outside the markers survives a re-sync. Shared by AGENTS.md
// (Markdown, hence HTML comments) — extracted so the same convention can be
// reused for a different host file format (see codexOllamaConfigToml below,
// which needs TOML's own `#` comment syntax instead).
function mergeMarkedRegion(existing, blockText, markerRe) {
  if (existing == null) return blockText;
  return markerRe.test(existing) ? existing.replace(markerRe, blockText) : existing.trimEnd() + '\n\n' + blockText;
}
const AGENTS_MD_MARKER_RE = /<!-- CONCERTINO:BEGIN[\s\S]*?<!-- CONCERTINO:END -->\n?/;

// `.codex/config.toml`'s `[model_providers.ollama]` block (design.md
// Decision 3) — a NEW, narrowly-scoped Concertino-managed file class (Codex's
// own config.toml is otherwise a user/global file Concertino has never
// rendered into before this ticket). Renders once per project whenever
// "codex" is in providers.ollama.harnesses, regardless of which individual
// roles end up Ollama-routed. TOML has no HTML-comment equivalent, so the
// merge-marker convention AGENTS.md uses is adapted to TOML's own `#`
// comment syntax — same regex-delimited-region mechanism, different host
// syntax.
const CODEX_CONFIG_TOML_MARKER_RE = /# CONCERTINO:BEGIN[\s\S]*?# CONCERTINO:END\n?/;
function codexOllamaConfigToml(c) {
  const ollama = c.providers.ollama;
  const lines = [
    '# CONCERTINO:BEGIN (generated by `concertino sync` — edit concertino.config.json, not here)',
    '[model_providers.ollama]',
    'name = "Ollama (local)"',
    'base_url = "' + ollama.baseUrl + '"',
    'wire_api = "chat"',
  ];
  if (ollama.apiKeyEnv) lines.push('env_key = "' + ollama.apiKeyEnv + '"');
  lines.push('# CONCERTINO:END', '');
  return lines.join('\n');
}

function emitCodex(c, out, core, dry) {
  const header = read(path.join(ADAPTERS, 'codex', 'header.md')).split('{{project}}').join(c.project.name);
  const roleSections = ['orchestrator', 'executor', 'evaluator', 'skeptic', 'auditor'].map((role) => {
    const body = renderBody(read(path.join(core, 'roles', role + '.md')), c, 'codex');
    return '## Role: ' + role[0].toUpperCase() + role.slice(1) + '\n\n' + body;
  }).join('\n\n---\n\n');
  let blockText = header.replace('<!-- CONCERTINO:ROLES -->', roleSections)
    + '\n\n<!-- CONCERTINO:END -->\n';

  const agentsPath = path.join(out, 'AGENTS.md');
  const full = mergeMarkedRegion(exists(agentsPath) ? read(agentsPath) : null, blockText, AGENTS_MD_MARKER_RE);
  write(agentsPath, full, dry);

  const tmpl = read(path.join(ADAPTERS, 'codex', 'agent.toml.tmpl'));
  const meta = JSON.parse(read(path.join(ADAPTERS, 'claude-code', 'agents.json')));
  for (const role of ['executor', 'evaluator', 'auditor']) {
    const body = renderBody(readRoleFile(role, out, core), c, 'codex');
    const desc = meta.roles[role].description.split('{{project}}').join(c.project.name);
    const toml = tmpl.split('{{role}}').join(role)
      .split('{{description}}').join(desc.replace(/"/g, '\\"'))
      .split('{{model}}').join(resolveModel(c, 'codex', role))
      .split('{{model_provider}}').join(codexModelProviderLine(c, role))
      .split('{{body}}').join(body);
    write(path.join(out, '.codex', 'agents', 'concertino-' + role + '.toml'), '# concertino:sync v' + VERSION + '\n' + toml, dry);
  }
  copy(path.join(ADAPTERS, 'codex', 'prompt.md'), path.join(out, '.codex', 'prompts', 'concertino-deliver.md'), dry);
  if (!dry) console.log('  ' + green('wrote') + ' ' + path.join(out, '.codex', 'prompts', 'concertino-deliver.md'));

  if ((c.providers.ollama && (c.providers.ollama.harnesses || []).includes('codex'))) {
    const configPath = path.join(out, '.codex', 'config.toml');
    const merged = mergeMarkedRegion(exists(configPath) ? read(configPath) : null, codexOllamaConfigToml(c), CODEX_CONFIG_TOML_MARKER_RE);
    write(configPath, merged, dry);
  }
}

// ---------- OpenCode adapter ------------------------------------------------
// Research findings (tasks.md 4.1, design.md Open Questions 1-3), confirmed
// against the sst/opencode (opencode.ai) source and docs
// (packages/web/src/content/docs/{config,agents,commands,providers}.mdx and
// packages/opencode/src/index.ts). Kept here, in source, rather than atop the
// adapter template files themselves: adapters/opencode/prompt.md's own YAML
// frontmatter must be the literal first bytes of the rendered file (a
// leading HTML comment there breaks OpenCode's frontmatter parser), and
// adapters/opencode/header.md gets prepended into a rendered agent's actual
// system-prompt body — shipping maintainer notes into every orchestrator
// invocation would be pure token waste, not documentation.
//
// - Native project config: `opencode.json` (or `opencode.jsonc`) at the
//   project root — JSON, deep-merged with global/remote config, so a
//   Concertino-managed sub-key (`provider.ollama`) can be written without
//   disturbing unrelated hand-authored keys.
// - Agent definitions: Markdown files with YAML frontmatter
//   (`description`/`mode`/`model`/`permission`) under `.opencode/agents/`
//   (plural — the modern convention; `.opencode/agent/` singular is also
//   accepted for back-compat). `mode: primary` agents are the ones a session
//   can be switched into directly (and what a command's own `agent:`
//   frontmatter field selects); `mode: subagent` agents are invoked via the
//   Task tool or `@name` mention.
// - Delivery command: Markdown files with YAML frontmatter
//   (`description`/`agent`/`model`) under `.opencode/commands/`, invoked as
//   `/concertino-deliver` — the same `$ARGUMENTS` placeholder Claude Code's
//   command file uses.
// - Ollama provider: `provider.ollama` = `{ npm: "@ai-sdk/openai-compatible",
//   name, options: { baseURL, apiKey }, models: { <id>: { name } } }` — the
//   OpenAI-compatible provider shape, `options.apiKey` supporting
//   `{env:VAR}` substitution for a credential env var name (never the value).
// - Runtime-identity signal (design.md Decision 6): confirmed, not guessed —
//   `packages/opencode/src/index.ts`'s CLI entrypoint unconditionally sets
//   `process.env.OPENCODE = "1"` (and `OPENCODE_PID`) in its own process
//   before dispatching any subcommand; the bash tool spawns child processes
//   with the inherited environment (no explicit `env` override in
//   `packages/core/src/tool/bash.ts`), so `OPENCODE` is present, non-empty,
//   in any shell command OpenCode's agent runs — including
//   `setup-worktree.sh`. See core/scripts/setup-worktree.sh's detect_harness().
// - Multi-agent dispatch (design.md Decision 5 / Open Question 1): OpenCode
//   has a genuine subagent/Task-tool mechanism (primary agents can invoke
//   `mode: subagent` agents and receive a result), but no publicly documented
//   guarantee of Claude Code's warm-resume-across-turns semantics
//   (`SendMessage` to a suspended agent). Per design.md's stated preference
//   for understating rather than overstating a harness's capability, this
//   adapter defaults to the conservative, Codex-like sequential-single-thread
//   description, with the Task tool documented as an optional worker-dispatch
//   path (parallel to Codex's optional `spawn_agents_on_csv`) — never a
//   required one.
const OPENCODE_ROLES = ['orchestrator', 'executor', 'evaluator', 'skeptic', 'auditor'];

// Mirrors Claude Code's baseTools shape (design.md Decision 5's "reuse
// adapters/claude-code/agents.json for shared per-role metadata where
// compatible"): orchestrator/executor may Edit; evaluator/skeptic/auditor
// may Write (reports) but not Edit source — best-effort tool-permission
// parity with the other two harnesses' per-role tool sets, not a strict
// mapping (OpenCode's permission model is shaped differently).
function opencodePermission(role) {
  return ['evaluator', 'skeptic', 'auditor'].includes(role) ? { edit: 'deny' } : undefined;
}

function renderOpencodeAgentMd(c, out, core, role, meta, header) {
  const r = meta.roles[role];
  const desc = r.description.split('{{project}}').join(c.project.name);
  const model = resolveModel(c, 'opencode', role);
  const mode = role === 'orchestrator' ? 'primary' : 'subagent';
  const perm = opencodePermission(role);
  const fm = [
    '---',
    '# concertino:sync v' + VERSION,
    'description: ' + JSON.stringify(desc),
    'mode: ' + mode,
    'model: ' + model,
  ];
  if (perm) {
    fm.push('permission:');
    for (const k of Object.keys(perm)) fm.push('  ' + k + ': ' + perm[k]);
  }
  fm.push('---', '');
  const body = renderBody(readRoleFile(role, out, core), c, 'opencode');
  // Only the orchestrator (the primary agent a session is switched into via
  // `/concertino-deliver`'s `agent:` frontmatter) carries the shared header —
  // parallel to how Codex's header appears once, at the top of the single
  // AGENTS.md a Codex session reads in whole. The other four roles are
  // subagent system prompts; like Claude Code's own per-role files, they
  // carry only their own role content.
  const prefix = role === 'orchestrator' ? header + '\n\n' : '';
  return fm.join('\n') + prefix + body;
}

// opencode.json is ordinary JSON (no comment syntax to hide a marked region
// in), so instead of AGENTS.md/config.toml's regex-delimited text region,
// this is a structural key-level merge: only the Concertino-managed
// `provider.ollama` key is set, every other top-level key (and every other
// `provider.<id>` entry) in an existing hand-authored opencode.json survives
// untouched.
function mergeOpencodeJson(existing, c) {
  let obj = {};
  if (existing != null) {
    try { obj = JSON.parse(existing); } catch (_) { obj = {}; }
  }
  if (!obj['$schema']) obj['$schema'] = 'https://opencode.ai/config.json';
  const ollama = c.providers.ollama;
  if (ollama && (ollama.harnesses || []).includes('opencode')) {
    obj.provider = obj.provider || {};
    const models = {};
    for (const id of Object.values(ollama.models || {})) models[id] = { name: id };
    obj.provider.ollama = {
      npm: '@ai-sdk/openai-compatible',
      name: 'Ollama (local)',
      // Ollama's OpenAI-compatible API is served under /v1 — baseUrl itself
      // is Ollama's own bare API root (see the schema's own baseUrl
      // description); this adapter appends what OpenCode's provider shape
      // specifically requires, exactly as Codex's own adapter separately
      // decides what it needs from the same baseUrl (design.md Decision 1).
      options: Object.assign(
        { baseURL: ollama.baseUrl.replace(/\/+$/, '') + '/v1' },
        ollama.apiKeyEnv ? { apiKey: '{env:' + ollama.apiKeyEnv + '}' } : {}
      ),
      models,
    };
  }
  return JSON.stringify(obj, null, 2) + '\n';
}

function emitOpencode(c, out, core, dry) {
  const meta = JSON.parse(read(path.join(ADAPTERS, 'claude-code', 'agents.json')));
  const header = read(path.join(ADAPTERS, 'opencode', 'header.md')).split('{{project}}').join(c.project.name);
  for (const role of OPENCODE_ROLES) {
    write(path.join(out, '.opencode', 'agents', 'concertino-' + role + '.md'),
      renderOpencodeAgentMd(c, out, core, role, meta, header), dry);
  }
  const cmd = read(path.join(ADAPTERS, 'opencode', 'prompt.md'))
    .split('{{project}}').join(c.project.name)
    .split('{{idExample}}').join(c.ticketProvider.idExample);
  write(path.join(out, '.opencode', 'commands', 'concertino-deliver.md'), cmd, dry);

  const cfgPath = path.join(out, 'opencode.json');
  const merged = mergeOpencodeJson(exists(cfgPath) ? read(cfgPath) : null, c);
  write(cfgPath, merged, dry);
}

// ---------- copy shared assets into the project --------------------------
function copyAssets(out, core, dry, withScripts) {
  for (const f of fs.readdirSync(path.join(core, 'laws')))
    copy(path.join(core, 'laws', f), path.join(out, '.concertino', 'laws', f), dry);
  copy(path.join(core, 'workflow-state.template.md'), path.join(out, '.concertino', 'workflow-state.template.md'), dry);
  if (withScripts) {
    for (const f of fs.readdirSync(path.join(core, 'scripts'))) {
      const dest = path.join(out, 'scripts', 'concertino', f);
      copy(path.join(core, 'scripts', f), dest, dry);
      if (!dry && f.endsWith('.sh')) fs.chmodSync(dest, 0o755);
    }
  }
  if (!dry) console.log('  ' + green('refreshed') + ' .concertino/ assets' + (withScripts ? ' + scripts/concertino/' : ''));
}

module.exports = {
  emitClaude, emitCodex, emitOpencode, copyAssets,
  codexModelProviderLine, mergeMarkedRegion, codexOllamaConfigToml,
  CODEX_CONFIG_TOML_MARKER_RE, OPENCODE_ROLES, renderOpencodeAgentMd,
  mergeOpencodeJson,
};
